### ISSUE TITLE
Block Issues? Is this an Bug on 1.20.1?

### ISSUE THREAD

**Issue by suerion** [yeelp/MCCE#1]
Hey, we don't know, if this should been as it is?

Here some Screens to look on the issues?

![grafik](https://github.com/yeelp/MCCE/assets/55131959/747b9db7-bee9-444f-891e-75d9c8a862ec)
![grafik](https://github.com/yeelp/MCCE/assets/55131959/5c25ac02-1b9e-495b-87c7-7d819eda61db)
![grafik](https://github.com/yeelp/MCCE/assets/55131959/1ea5beeb-5c6e-41f8-b4ba-833caeec3c50)

**Comment by yeelp** [comment]
This is intended! It's a specific effect, you can read more about it [here](https://github.com/yeelp/MCCE/wiki/Chaos-Effect:-Item-Evaporation) if you're curious.
